Importer DBKKs =mdb= database(fra 2003) ind i en ny sqlite db.

Boginfo hentes fra http://openlibrary.org (=olib=). Hvis bogen ikke findes der, forsøges der at hente info fra google(=goob=) og dernæst fra DBKKs mdb-database, hvorefter bogen oprettes i =olib=.

Alle bøger i =olib= har et unikt =olid= (tilsvarende =ISBN=) der tildeles automatisk ved ny bogoprettelse. Derfor bruges =olid= som primær id. Det betyder også at ældre bøger uden =ISBN= nemt kan indekseres.

Har DBKKs db yderligere info end der findes på =olib=, opdateres =olib= med dette.

Det primære script er =mdb_read.py=. Det læser =bjerg2003.mdb=, parser info og opdaterer sqlite databasen.


* Opret SQlite db
Før scriptet køres, skal databasen oprettes. Det gøres med

  sqlite3 < createdb.sqlite
* Install
For at køre scriptet, skal følgende installeres,
    pip install openlibrary-client isbnlib
* API
fx, =isbn=184195215X= (isbn10),
** =olib=
https://openlibrary.org/dev/docs/api/books

example:
[[https://openlibrary.org/api/books?bibkeys=ISBN:184195215X&jscmd=data&format=json][https://openlibrary.org/api/books?bibkeys=ISBN:184195215X&jscmd=data&format=json]]
** =goob=
https://developers.google.com/books/docs/v1/reference/volumes

example:
[[https://www.googleapis.com/books/v1/volumes?q=isbn:184195215X&fields=items/volumeInfo(title,subtitle,authors,publisher,publishedDate,language,industryIdentifiers,pageCount,imageLinks.thumbnail,categories)&maxResults=1][https://www.googleapis.com/books/v1/volumes?q=isbn:184195215X&fields=items/volumeInfo(title,subtitle,authors,publisher,publishedDate,language,industryIdentifiers,pageCount,imageLinks.thumbnail,categories)&maxResults=1]]
